package com.itgorillaz.core.model;

public enum EmailRequestStatusCode {

	INVALID_PAYLOAD,
	ATTACHMENT_NOT_FOUND,
	MAX_ATTACHMENT_SIZE_EXCEEDED,
	SUPPRESSED_RECIPIENT_FOUND,
	EMAIL_BOUNCED,
	COMPLAINT_REPORTED,
	FAILED_ON_SMTP_CHECK,
	MAIN_RECIPIENT_IS_UNDELIVERABLE,
	EMAIL_REQUEST_NOT_FOUND,
	SENDER_IDENTITY_NOT_VERIFIED,
	MAX_RECIPIENTS_EXCEEDED,
	APPLICATION_CLIENT_NOT_FOUND,
	APPLICATION_CLIENT_NOT_ENABLED,
	APPLICATION_DAILY_QUOTA_EXCEEDED,
	UNEXPECTED_ERROR,
	OK
	
}
